//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUToDoList
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBoard()
        {
            this.tblList = new HashSet<tblList>();
        }
        [Display(Name = "Tablero ")]
        public int id_board { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Nombre del Tablero requerdio"), MaxLength(55)]
        [Display(Name = "Nombre del Tablero ")]
        public string name_board { get; set; }

        [Display(Name = "Jefe ")]
        public int id_owner { get; set; }

        [Display(Name = "Participantes ")]
        public string id_participants { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblList> tblList { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
