//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUToDoList
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblList()
        {
            this.tblTask = new HashSet<tblTask>();
        }

        [Display(Name = "Lista ")]
        public int id_list { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Lista requeridos"), MaxLength(55)]
        [Display(Name = "Listas ")]
        public string name_list { get; set; }

        [Display(Name = "Tablero")]
        public int id_board { get; set; }
    
        public virtual tblBoard tblBoard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTask> tblTask { get; set; }
    }
}
