//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUToDoList
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblTask
    {
        [Display(Name = "Tarea ")]
        public int id_task { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Título requeridos"), MaxLength(55)]
        [Display(Name = "Titulo ")]
        public string title { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Descripción requerida"), MaxLength(55)]
        [Display(Name = "Descripción")]
        public string descr { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Asignado a")]
        public int asigned_to { get; set; }

        [Display(Name = "Lista ")]
        public int id_list { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Asignaciones")]
        public virtual tblList tblList { get; set; }
    }
}
